# Generated by Django 2.1.5 on 2019-03-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_customer_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_customer',
            name='r_date',
            field=models.DateField(auto_now=True),
        ),
    ]
