# Generated by Django 2.1.7 on 2019-04-06 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20190305_2120'),
        ('employee', '0005_auto_20190306_1923'),
    ]

    operations = [
    ]
