# Generated by Django 2.1.5 on 2019-03-02 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_customer',
            old_name='e_id',
            new_name='e',
        ),
        migrations.RemoveField(
            model_name='employee_customer',
            name='c_id',
        ),
    ]
